[build]
  publish = "frontend"
  command = "echo 'No build step; static files in frontend/'"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_BACKEND_URL/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
